USE PREMIER3;

CREATE TABLE EQUIPOS (
    ID_EQUIPO INT PRIMARY KEY,
    NOMBRE VARCHAR(255),
	AÑO_FUNDACION INT
);

CREATE TABLE JUGADORES (
	ID_JUGADOR INT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    APELLIDO VARCHAR(255),
    NACIMIENTO DATE,
    NACIONALIDAD VARCHAR(255),
    POSICION VARCHAR(50),
	ID_EQUIPO INT,
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS (ID_EQUIPO)
);

CREATE TABLE ESTADIOS (
    ID_ESTADIO  INT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    CAPACIDAD INT,
    CIUDAD VARCHAR(255),
    ID_EQUIPO INT,
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS (ID_EQUIPO)
);

CREATE TABLE ARBITROS (
    ID_ARBITRO INT PRIMARY KEY,
    NOMBRE VARCHAR(255),
    APELLIDO VARCHAR(255),
    NACIONALIDAD VARCHAR(255)
);

CREATE TABLE PARTIDOS (
    ID_PARTIDO INT PRIMARY KEY,
	ID_EQUIPO_LOCAL INT,
    ID_EQUIPO_VISITANTE INT,
	FECHA DATE, 
    ID_ARBITRO INT,
    ID_ESTADIO INT,
    FOREIGN KEY (ID_ESTADIO) REFERENCES ESTADIOS (ID_ESTADIO),
	FOREIGN key (ID_ARBITRO) REFERENCES ARBITROS (ID_ARBITRO),
    FOREIGN key (ID_EQUIPO_LOCAL) REFERENCES EQUIPOS (ID_EQUIPO),
    FOREIGN key (ID_EQUIPO_VISITANTE) REFERENCES EQUIPOS (ID_EQUIPO)
);

CREATE TABLE ENTRENADORES (
    NOMBRE VARCHAR(255),
    APELLIDO VARCHAR(255),
    ID_EQUIPO INT,
    ID_ENTRENADOR INT,
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS (ID_EQUIPO)
);




